name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install jackd libjack0 libjack-dev
      # This is required for the tests, but we start it earlier since it may
      # take a while to initialize.
      - name: Start dummy JACK server
        run: jackd -r -ddummy -r44100 -p1024 &
      - name: Build (No Features)
        run: cargo build --verbose --no-default-features
      - name: Build (metadata)
        run: cargo build --verbose --no-default-features --features metadata
      - name: Run Tests
        run: cargo test --verbose --all-features
        env:
          RUST_TEST_THREADS: 1
